routes/web.php
<?php
use Illuminate\Support\Facades\Artisan;
/*

php artisan cache:clear
php artisan route:clear
php artisan config:clear
php artisan config:cache
php artisan view:clear

*/
Route::get('clear', function () {
    Artisan::call('data:clear');
    return redirect()->route('home');
});

Auth::routes([
    'verify' => true,
    'reset' => true
]);

Route::match(['get', 'post'], 'register', function () {
    abort(404);
});

Route::prefix('/')->group(function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('kiem-tra-cmnd', 'HomeController@kiemtra_cmnd')->name('kiemtra_cmnd');

    Route::get('thong-tin-lien-he', 'LienHeController@index')->name('lienhe');
    Route::get('noi-quy-nhan-lop', 'NoiQuyController@index')->name('noiquy');
    Route::get('hoc-phi-tham-khao', 'HocPhiController@index')->name('hocphi');
    Route::get('tai-lieu-hoc-tap', 'TaiLieuController@index')->name('tailieu');
    Route::get('tai-lieu/{slug}', 'TaiLieuController@chitiet')->name('chitiettailieu');
    Route::get('tin-tuc', 'TinTucController@index')->name('tintuc');
    Route::get('tin-tuc/{slug}', 'TinTucController@chitiet')->name('chitiettintuc');
    Route::resource('dang-ky-tim-gia-su', 'DangKyHocController')->only(['index', 'store']);
    Route::resource('dang-ky-lam-gia-su', 'DangKyGiaSuController')->only(['index', 'store']);

    Route::get('danh-sach-lop-hien-co', 'DanhSachLopController@index')->name('danhsachlop');
    Route::post('danh-sach-lop-hien-co', 'DanhSachLopController@timkiemlop')->name('timkiemlop');

    Route::get('danh-sach-gia-su', 'DanhSachGiaSuController@index')->name('danhsachgiasu');
    Route::post('danh-sach-gia-su', 'DanhSachGiaSuController@timkiemgiasu')->name('timkiemgiasu');

    Route::get('gia-su-{slug}', 'DanhSachLopController@chitietlop')->name('chitietlop');
    Route::post('gia-su-{slug}', 'DanhSachLopController@dangkyday')->name('dangkyday');

    Route::get('d', function () {
        return redirect()->route('admin');
    });
    Route::get('thumb.php', 'HomeController@thumb');
});

Route::prefix('giasu')->group(function() {
    Route::get('/', 'GiaSuController@index')->name('giasu');
    Route::post('cap-nhat-thong-tin', 'GiaSuController@store')->name('giasu.store');
    Route::get('thay-doi-mat-khau', 'GiaSuController@dmk')->name('giasu.dmk');
    Route::post('thay-doi-mat-khau', 'GiaSuController@tdmk')->name('giasu.tdmk');
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('giasu.login');
    Route::post('login', 'Auth\LoginController@login')->name('giasu.login.submit');
    Route::prefix('password')->group(function() {
        Route::post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    });
    Route::prefix('email')->group(function() {
        Route::post('resend', 'Auth\VerificationController@resend')->name('verification.resend');
        Route::get('verify', 'Auth\VerificationController@show')->name('verification.notice');
        Route::get('verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
    });
});

Route::prefix('admin')->group(function() {
    Route::get('/', 'AdminController@index')->name('admin');
    Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    Route::prefix('profile')->group(function() {
        Route::get('/', 'AdminController@profile')->name('admin.profile');
        Route::post('/', 'AdminController@profile_store')->name('admin.profile_store');
        Route::post('chang-password', 'AdminController@profile_changePassword')->name('admin.profile_changePassword');
        Route::get('checkEmail', 'AdminController@profile_checkEmail')->name('admin.profile_checkEmail');
    });

    Route::prefix('password')->group(function() {
        Route::post('email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::get('reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('reset', 'Auth\AdminResetPasswordController@reset')->name('admin.password.update');
    });
    Route::prefix('email')->group(function() {
        Route::post('resend', 'Auth\AdminVerificationController@resend')->name('admin.verification.resend');
        Route::get('verify', 'Auth\AdminVerificationController@show')->name('admin.verification.notice');
        Route::get('verify/{id}', 'Auth\AdminVerificationController@verify')->name('admin.verification.verify');
    });

    Route::prefix('nguoi-dung')->group(function() {
        Route::get('/', 'AdminController@nguoidung')->name('admin.nguoidung');
        Route::get('danh-sach', 'AdminController@ds_nguoidung')->name('admin.ds_nguoidung');
        Route::post('them', 'AdminController@them_nguoidung')->name('admin.them_nguoidung');
        Route::post('thay-doi', 'AdminController@thaydoi_nguoidung')->name('admin.thaydoi_nguoidung');
        Route::delete('xoa', 'AdminController@xoa_nguoidung')->name('admin.xoa_nguoidung');
        Route::post('reset-password', 'AdminController@resetpw_nguoidung')->name('admin.resetpw_nguoidung');
    });

    Route::prefix('gia-su')->group(function() {
        Route::get('/', 'AdminController@giasu')->name('admin.giasu');
        Route::get('danh-sach', 'AdminController@ds_giasu')->name('admin.ds_giasu');
        Route::post('thay-doi', 'AdminController@thaydoi_giasu')->name('admin.thaydoi_giasu');
        Route::post('tieu-bieu', 'AdminController@tieubieu_giasu')->name('admin.tieubieu_giasu');
        Route::get('lay-thong-tin', 'AdminController@laythongtin_giasu')->name('admin.laythongtin_giasu');
        Route::delete('xoa', 'AdminController@xoa_giasu')->name('admin.xoa_giasu');
    });

    Route::prefix('danh-sach-dang-ky')->group(function() {
        Route::get('/', 'AdminController@dangky')->name('admin.dangky');
        Route::get('danh-sach', 'AdminController@ds_dangky')->name('admin.ds_dangky');
        Route::post('thay-doi', 'AdminController@thaydoi_dangky')->name('admin.thaydoi_dangky');
        Route::get('kiem-tra-ma-lop', 'AdminController@kiemtra_malop')->name('admin.kiemtra_malop');
        Route::get('lay-thong-tin', 'AdminController@laythongtin_dangky')->name('admin.laythongtin_dangky');
        Route::post('cap-nhat', 'AdminController@capnhat_dangky')->name('admin.capnhat_dangky');
        Route::delete('xoa', 'AdminController@xoa_dangky')->name('admin.xoa_dangky');
    });

    Route::prefix('danh-sach-lop')->group(function() {
        Route::get('/', 'AdminController@lop')->name('admin.dslop');
        Route::get('danh-sach', 'AdminController@ds_lop')->name('admin.ds_molop');
        Route::post('thay-doi', 'AdminController@thaydoi_dslop')->name('admin.thaydoi_dslop');
        Route::get('lay-thong-tin', 'AdminController@laythongtin_dslop')->name('admin.laythongtin_dslop');
        Route::post('cap-nhat', 'AdminController@capnhat_dslop')->name('admin.capnhat_dslop');
        Route::delete('xoa', 'AdminController@xoa_dslop')->name('admin.xoa_dslop');
    });

    Route::prefix('danh-sach-nhan-day')->group(function() {
        Route::get('/', 'AdminController@nhanday')->name('admin.dsnhanday');
        Route::get('lay-thong-tin', 'AdminController@laythongtin_nhanday')->name('admin.laythongtin_nhanday');
        Route::post('thay-doi', 'AdminController@thaydoi_nhanday')->name('admin.thaydoi_nhanday');
        Route::post('thay-doi-gia-su', 'AdminController@thaydoigs_nhanday')->name('admin.thaydoigs_nhanday');
        Route::delete('xoa', 'AdminController@xoa_nhanday')->name('admin.xoa_nhanday');
    });

    Route::prefix('bai-viet')->group(function() {
        Route::get('/', 'AdminController@baiviet')->name('admin.baiviet');
        Route::get('danh-sach', 'AdminController@ds_baiviet')->name('admin.ds_baiviet');
        Route::get('them', 'AdminController@baiviet_them')->name('admin.baiviet_them');
        Route::post('them', 'AdminController@baiviet_luu')->name('admin.baiviet_luu');
        Route::get('xem/{id}', 'AdminController@baiviet_xem')->name('admin.baiviet_xem');
        Route::post('xem', 'AdminController@baiviet_xem_luu')->name('admin.baiviet_xem_luu');
        Route::delete('xoa', 'AdminController@baiviet_xoa')->name('admin.baiviet_xoa');
    });

    Route::prefix('storage')->group(function() {
        Route::get('/', 'AdminController@storage')->name('admin.storage');
        Route::get('explorer', function () {
            return view('admin.storage.explorer');
        });
    });

    Route::prefix('system')->group(function() {
        Route::get('/', 'AdminController@system')->name('admin.system');
        Route::get('explorer', function () {
            return view('admin.system.explorer');
        });
    });

    Route::prefix('tools')->group(function() {
        Route::get('/', 'AdminController@tools')->name('admin.tools');
        Route::post('/', 'AdminController@tools_store')->name('admin.tools.store');

        Route::get('smtp', 'AdminController@smtp')->name('admin.tools.smtp');
        Route::get('seo', 'AdminController@seo')->name('admin.tools.seo');
        Route::get('chat', 'AdminController@chat')->name('admin.tools.chat');
        Route::get('lien-he', 'AdminController@lienhe')->name('admin.tools.lienhe');
        Route::get('clear', 'AdminController@clear')->name('admin.tools.clear');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Đăng nhập') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->holot . ' ' . Auth::user()->ten }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Đăng xuất') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="content-language" content="vi">
    <meta http-equiv="Cache-control" content="private, max-age=604800">
    <title>@yield('title'){{config('app.title')}}</title>

    <!-- ROBOTS -->
    <meta name="googlebot" content="noarchive" />
    <meta name="robots" content="noarchive" />

    <!-- GENERAL GOOGLE SEARCH META -->
    <meta name="abstract" content="{{config('app.title')}}">
    <meta rel="canonical" href="@yield('canonical')">
    <meta name="RATING" content="GENERAL">
    <meta name="description" content="{{config('app.description')}}">
    <meta name="keywords" content="{{config('app.keywords')}}">
    <meta name="geo.placename" content="Ho Chi Minh, Viet Nam">
    <meta name="geo.posion" content="Ho Chi Minh, Viet Nam">
    <meta property="og:title" content="@yield('title'){{config('app.title')}}">
    <meta property="og:url" content="@yield('url')">
    <meta property="og:site_name" content="{{config('app.name')}}">
    <meta property="og:description" content="{{config('app.description')}}">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="vi_VN">
    <meta property="og:image" content="{{asset(config('app.banner').'?v=4.1')}}">
    <meta property="og:image:secure_url" content="{{asset(config('app.banner').'?v=4.1')}}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:rich_attachment" content="true">
    <meta name="google-site-verification" content="{{config('google.verification')}}">
    <meta name="msvalidate.01" content="{{config('bing.verification')}}">
    <!-- FACEBOOK OPEN GRAPH -->
    <meta property="fb:app_id" content="{{config('facebook.id')}}">
    <meta property="article:publisher" content="{{config('facebook.url')}}">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:description" content="{{config('app.description')}}">
    <meta name="twitter:title" content="@yield('title'){{config('app.title')}}">
    <meta name="twitter:image" content="{{asset(config('app.banner').'?v=4.1')}}">
    <meta name="author" content="giasuthanhdanh.com, Nguyễn Linh - ntt.nguyenlinh@gmail.com">
    <meta name="copyright" content="Copyright 2019 - {{config('app.name')}}">
    <link rel='shortlink' href='{{config('app.url')}}'>

    <link rel="icon" href="{{asset(config('app.icon').'?v=4.1')}}" type="image/x-icon">
    <link rel="apple-touch-icon image_src" href="{{asset(config('app.icon').'?v=4.1')}}">

    <link rel="stylesheet" href="{{asset('css/style.css?v=4.1')}}" media="screen,print">
    <link rel="stylesheet" href="{{asset('font-awesome/css/all.min.css?v=4.1')}}">
    <link rel="stylesheet" href="{{asset('css/custom.css?v=4.1')}}">
    <link rel="stylesheet" href="{{asset('css/faq.css?v=4.1')}}">
    <link rel="stylesheet" href="{{asset('css/sweetalert2.min.css?v=4.1')}}">
</head>
<body>
    <div id="background"></div>
    <div class="wrapper">
        <div class="header">
            <img class="logo" src="{{asset('images/logo.png')}}">
            <ul class="menu clearfix">
                <li class="m1">
                    <a href="{{route('home')}}" title="{{config('app.title')}}">TRANG CHỦ</a>
                </li>
                <li class="m2">
                    <a href="{{route('dang-ky-tim-gia-su.index')}}" title="Đăng ký tìm gia sư">ĐĂNG KÝ TÌM GIA SƯ</a>
                </li>

                <li class="m5"></li>

                <li class="m3">
                    <a href="{{route('danhsachlop')}}" title="Lớp hiện có">LỚP HIỆN CÓ</a>
                </li>

                <li class="m4">
                    <a href="{{route('noiquy')}}" title="Nội quy nhận lớp">NỘI QUY NHẬN LỚP</a>
                </li>
            </ul>

            <ul class="menu clearfix" style="margin-top:-4px; padding-top:0;">
                <li class="m1">
                    <a href="{{route('tailieu')}}" title="tài liệu học tập">TÀI LIỆU HỌC TẬP</a>
                </li>
                <li class="m2">
                    <a href="{{route('hocphi')}}" title="Học phí tham khảo">HỌC PHÍ THAM KHẢO</a>
                </li>

                <li class="m5"></li>

                <li class="m3">
                    <a href="{{route('dang-ky-lam-gia-su.index')}}" title="Đăng ký thành viên">ĐĂNG KÝ THÀNH VIÊN</a>
                </li>

                <li class="m4">
                    <a href="{{route('lienhe')}}" title="Thông tin liên hệ">THÔNG TIN LIÊN HỆ</a>
                </li>
            </ul>

        </div>
        <div class="slideOut">
            <div id="slider" class="swipe">
                <div class="swipe-wrap">
                    <div>
                        <img src="/thumb.php?src={{asset('images/gia-su-thanh-danh-day-kem-tai-nha-1.jpg?v=4.1')}}"/>
                    </div>
                    <div>
                        <img src="/thumb.php?src={{asset('images/gia-su-thanh-danh-day-kem-tai-nha-2.jpg?v=4.1')}}"/>
                    </div>
                    <div>
                        <img src="/thumb.php?src={{asset('images/gia-su-thanh-danh-day-kem-tai-nha-3.jpg?v=4.1')}}"/>
                    </div>
                    <div>
                        <img src="/thumb.php?src={{asset('images/gia-su-thanh-danh-day-kem-tai-nha-4.jpg?v=4.1')}}"/>
                    </div>
                    <div>
                        <img src="/thumb.php?src={{asset('images/gia-su-thanh-danh-day-kem-tai-nha-5.jpg?v=4.1')}}"/>
                    </div>
                </div>
            </div>
            <p class="slide_top">
                <img src="/thumb.php?src={{asset('images/gia-su-thanh-danh-day-kem-tai-nha.png?v=4.1')}}"/>
            </p>
            <p class="slide_bottom">
                <img src="/thumb.php?src={{asset('images/slide-bottom.jpg?v=4.1')}}"/>
            </p>
            <div class="slide_left">
                <p style="font-size: 14pt; font-weight:900; text-align: center; color:#1c87c9;">
                    Phụ huynh - học viên
                    <span style="text-align: center; font-size: 13pt;" class="blink-two">Tìm gia sư</span>
                </p>
                <p style="font-size: 13pt; margin-top: 5pt; margin-left:-10px; color:red;" class="blink-two">{{config('app.sdt1')}}</p>
            </div>
            <div class="slide_right">
                <p style="font-size: 14pt; font-weight:900; text-align: center; color:#1c87c9; margin-left:50px;">
                    Giáo viên - sinh viên
                    <span class="blink-two" style="text-align: center; font-size: 13pt;">Tìm lớp dạy</span>
                </p>
                <p class="blink-two" style="font-size: 13pt; margin-top: 5pt; color:red; margin-right: -30px;">{{config('app.sdt2')}}</p>

                <div style="margin-top:20px; margin-right:-60px;">
                    <p style="text-align:center; padding:10px 30px; font-size: 16pt; font-style: oblique; color:rgba(255, 0, 255, 0.71);">
                        GIA SƯ CỦA SỰ
                    </p>
                    <p style="text-align:left; padding:10px 30px; font-size: 14pt; font-style: oblique; color:#80ffff;">
                        <blink class="blink-two"><i class="fal fa-check"></i> CHUYÊN NGHIỆP</blink>
                    </p>
                    <p style="text-align:left; padding:10px 30px; font-size: 14pt; font-style: oblique; color:#80ffff;">
                        <blink class="blink-two"><i class="fal fa-check"></i> TẬN TÂM</blink>
                    </p>
                    <p style="text-align:left; padding:10px 30px; font-size: 14pt; font-style: oblique; color:#80ffff;">
                        <blink class="blink-two"><i class="fal fa-check"></i> TRÁCH NHIỆM</blink>
                    </p>
                    <p style="text-align:left; padding:10px 30px; font-size: 14pt; font-style: oblique; color:#80ffff;">
                        <blink class="blink-two"><i class="fal fa-check"></i> HÀI LÒNG</blink>
                    </p>
                    <p style="text-align:left; padding:10px 30px; font-size: 14pt; font-style: oblique; color:#80ffff;">
                        <blink class="blink-two"><i class="fal fa-check"></i> VỮNG VÀNG KIẾN THỨC</blink>
                    </p>
                </div>
            </div>
        </div>

resources/views/layouts/home.blade.php
@include('layouts.header')
@section('content')
@show
<div class="col_r">
@include('giasu.bar_login')
@include('layouts.footer')